# Switches
set_property PACKAGE_PIN V17 [get_ports {input[0]}]
set_property PACKAGE_PIN V16 [get_ports {input[1]}]
set_property PACKAGE_PIN W16 [get_ports {input[2]}]
# set_property PACKAGE_PIN W17 [get_ports {input_b[1]}]
# set_property PACKAGE_PIN W15 [get_ports {input_a[2]}]
# set_property PACKAGE_PIN V15 [get_ports {input_b[2]}]
# set_property PACKAGE_PIN W14 [get_ports {input_a[3]}]
# set_property PACKAGE_PIN W13 [get_ports {input_b[3]}]
# set_property PACKAGE_PIN V2 [get_ports {input_a[4]}]
# set_property PACKAGE_PIN T3 [get_ports {input_b[4]}]
# set_property PACKAGE_PIN T2 [get_ports {input_a[5]}]
# set_property PACKAGE_PIN R3 [get_ports {input_b[5]}]
# set_property PACKAGE_PIN W2 [get_ports {input_a[6]}]
# set_property PACKAGE_PIN U1 [get_ports {input_b[6]}]
# set_property PACKAGE_PIN T1 [get_ports {input_a[7]}]
# set_property PACKAGE_PIN R2 [get_ports {input_b[7]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {output[0]}]
set_property PACKAGE_PIN E19 [get_ports {output[1]}]
set_property PACKAGE_PIN U19 [get_ports {output[2]}]
set_property PACKAGE_PIN V19 [get_ports {output[3]}]
set_property PACKAGE_PIN W18 [get_ports {output[4]}]
set_property PACKAGE_PIN U15 [get_ports {output[5]}]
set_property PACKAGE_PIN U14 [get_ports {output[6]}]
set_property PACKAGE_PIN V14 [get_ports {output[7]}]
# set_property PACKAGE_PIN V13 [get_ports {output[4]}]
# set_property PACKAGE_PIN V3 [get_ports {output[9]}]
# set_property PACKAGE_PIN W3 [get_ports {output[5]}]
# set_property PACKAGE_PIN U3 [get_ports {output[11]}]
# set_property PACKAGE_PIN P3 [get_ports {output[6]}]
# set_property PACKAGE_PIN N3 [get_ports {output[13]}]
# set_property PACKAGE_PIN P1 [get_ports {output[7]}]
# set_property PACKAGE_PIN L1 [get_ports {output[15]}]

set_property IOSTANDARD LVCMOS33 [all_inputs]
set_property IOSTANDARD LVCMOS33 [all_outputs]
